//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.1433.
// 
namespace SalesDeliveryCE7.WebRefSales {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ISalesService", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Delegate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XppObjectBase))]
    public partial class SalesService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SalesService() {
            this.Url = "http://172.17.0.50/HandHeldServices/SalesService.svc";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISalesService/FindSalesOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SalesTable FindSalesOrder([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string salesId) {
            object[] results = this.Invoke("FindSalesOrder", new object[] {
                        salesId});
            return ((SalesTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFindSalesOrder(string salesId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FindSalesOrder", new object[] {
                        salesId}, callback, asyncState);
        }
        
        /// <remarks/>
        public SalesTable EndFindSalesOrder(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SalesTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISalesService/FindPickingList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SalesTable FindPickingList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pickingId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string device) {
            object[] results = this.Invoke("FindPickingList", new object[] {
                        pickingId,
                        userName,
                        device});
            return ((SalesTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFindPickingList(string pickingId, string userName, string device, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FindPickingList", new object[] {
                        pickingId,
                        userName,
                        device}, callback, asyncState);
        }
        
        /// <remarks/>
        public SalesTable EndFindPickingList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SalesTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISalesService/ValidatePallets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
        public SalesLine[] ValidatePallets([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string salesId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string itemId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string configId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pickingId, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")] string[] pallets, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string device, long lineRecId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool lineRecIdSpecified) {
            object[] results = this.Invoke("ValidatePallets", new object[] {
                        salesId,
                        itemId,
                        configId,
                        pickingId,
                        pallets,
                        userName,
                        device,
                        lineRecId,
                        lineRecIdSpecified});
            return ((SalesLine[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginValidatePallets(string salesId, string itemId, string configId, string pickingId, string[] pallets, string userName, string device, long lineRecId, bool lineRecIdSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ValidatePallets", new object[] {
                        salesId,
                        itemId,
                        configId,
                        pickingId,
                        pallets,
                        userName,
                        device,
                        lineRecId,
                        lineRecIdSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public SalesLine[] EndValidatePallets(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SalesLine[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISalesService/CheckPalletAvailable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SalesLine CheckPalletAvailable([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string salesId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string itemId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string configId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pickingId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pallet, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string device, System.DateTime dtSave, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dtSaveSpecified, long lineRecId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool lineRecIdSpecified) {
            object[] results = this.Invoke("CheckPalletAvailable", new object[] {
                        salesId,
                        itemId,
                        configId,
                        pickingId,
                        pallet,
                        userName,
                        device,
                        dtSave,
                        dtSaveSpecified,
                        lineRecId,
                        lineRecIdSpecified});
            return ((SalesLine)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCheckPalletAvailable(string salesId, string itemId, string configId, string pickingId, string pallet, string userName, string device, System.DateTime dtSave, bool dtSaveSpecified, long lineRecId, bool lineRecIdSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CheckPalletAvailable", new object[] {
                        salesId,
                        itemId,
                        configId,
                        pickingId,
                        pallet,
                        userName,
                        device,
                        dtSave,
                        dtSaveSpecified,
                        lineRecId,
                        lineRecIdSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public SalesLine EndCheckPalletAvailable(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SalesLine)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISalesService/CheckPalletAvailableMulti", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
        public SalesLine[] CheckPalletAvailableMulti([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string salesId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string itemId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string configId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pickingId, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")] PalletItemContract[] pallets, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string device, long lineRecId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool lineRecIdSpecified) {
            object[] results = this.Invoke("CheckPalletAvailableMulti", new object[] {
                        salesId,
                        itemId,
                        configId,
                        pickingId,
                        pallets,
                        userName,
                        device,
                        lineRecId,
                        lineRecIdSpecified});
            return ((SalesLine[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCheckPalletAvailableMulti(string salesId, string itemId, string configId, string pickingId, PalletItemContract[] pallets, string userName, string device, long lineRecId, bool lineRecIdSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CheckPalletAvailableMulti", new object[] {
                        salesId,
                        itemId,
                        configId,
                        pickingId,
                        pallets,
                        userName,
                        device,
                        lineRecId,
                        lineRecIdSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public SalesLine[] EndCheckPalletAvailableMulti(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SalesLine[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISalesService/UnreservePallet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UnreservePallet([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pallet, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pickingId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string device) {
            object[] results = this.Invoke("UnreservePallet", new object[] {
                        pallet,
                        pickingId,
                        userName,
                        device});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUnreservePallet(string pallet, string pickingId, string userName, string device, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UnreservePallet", new object[] {
                        pallet,
                        pickingId,
                        userName,
                        device}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndUnreservePallet(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISalesService/GetLatestPallets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
        public SalesLine[] GetLatestPallets([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pickingId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string itemId) {
            object[] results = this.Invoke("GetLatestPallets", new object[] {
                        pickingId,
                        itemId});
            return ((SalesLine[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetLatestPallets(string pickingId, string itemId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetLatestPallets", new object[] {
                        pickingId,
                        itemId}, callback, asyncState);
        }
        
        /// <remarks/>
        public SalesLine[] EndGetLatestPallets(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SalesLine[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISalesService/SavePickingLoad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SavePickingLoad([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pickingId, System.DateTime startLoad, [System.Xml.Serialization.XmlIgnoreAttribute()] bool startLoadSpecified, System.DateTime stopLoad, [System.Xml.Serialization.XmlIgnoreAttribute()] bool stopLoadSpecified) {
            this.Invoke("SavePickingLoad", new object[] {
                        pickingId,
                        startLoad,
                        startLoadSpecified,
                        stopLoad,
                        stopLoadSpecified});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSavePickingLoad(string pickingId, System.DateTime startLoad, bool startLoadSpecified, System.DateTime stopLoad, bool stopLoadSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SavePickingLoad", new object[] {
                        pickingId,
                        startLoad,
                        startLoadSpecified,
                        stopLoad,
                        stopLoadSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSavePickingLoad(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISalesService/CustomersDeliveryByQty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
        public CustomerDeliveryContract[] CustomersDeliveryByQty(System.DateTime startDate, [System.Xml.Serialization.XmlIgnoreAttribute()] bool startDateSpecified, System.DateTime endDate, [System.Xml.Serialization.XmlIgnoreAttribute()] bool endDateSpecified) {
            object[] results = this.Invoke("CustomersDeliveryByQty", new object[] {
                        startDate,
                        startDateSpecified,
                        endDate,
                        endDateSpecified});
            return ((CustomerDeliveryContract[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCustomersDeliveryByQty(System.DateTime startDate, bool startDateSpecified, System.DateTime endDate, bool endDateSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CustomersDeliveryByQty", new object[] {
                        startDate,
                        startDateSpecified,
                        endDate,
                        endDateSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public CustomerDeliveryContract[] EndCustomersDeliveryByQty(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CustomerDeliveryContract[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISalesService/CustomersDeliveryByTrucks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
        public CustomerDeliveryContract[] CustomersDeliveryByTrucks(System.DateTime startDate, [System.Xml.Serialization.XmlIgnoreAttribute()] bool startDateSpecified, System.DateTime endDate, [System.Xml.Serialization.XmlIgnoreAttribute()] bool endDateSpecified) {
            object[] results = this.Invoke("CustomersDeliveryByTrucks", new object[] {
                        startDate,
                        startDateSpecified,
                        endDate,
                        endDateSpecified});
            return ((CustomerDeliveryContract[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCustomersDeliveryByTrucks(System.DateTime startDate, bool startDateSpecified, System.DateTime endDate, bool endDateSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CustomersDeliveryByTrucks", new object[] {
                        startDate,
                        startDateSpecified,
                        endDate,
                        endDateSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public CustomerDeliveryContract[] EndCustomersDeliveryByTrucks(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CustomerDeliveryContract[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISalesService/GetPing", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetPing() {
            object[] results = this.Invoke("GetPing", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPing(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPing", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetPing(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISalesService/ReceivePickingList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SalesTable ReceivePickingList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string device) {
            object[] results = this.Invoke("ReceivePickingList", new object[] {
                        userName,
                        device});
            return ((SalesTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReceivePickingList(string userName, string device, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReceivePickingList", new object[] {
                        userName,
                        device}, callback, asyncState);
        }
        
        /// <remarks/>
        public SalesTable EndReceivePickingList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SalesTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISalesService/SaveLoginHistory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SaveLoginHistory([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string device, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string deviceIp, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string projectName) {
            this.Invoke("SaveLoginHistory", new object[] {
                        userName,
                        device,
                        deviceIp,
                        projectName});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSaveLoginHistory(string userName, string device, string deviceIp, string projectName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SaveLoginHistory", new object[] {
                        userName,
                        device,
                        deviceIp,
                        projectName}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSaveLoginHistory(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISalesService/GetFGLines", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
        public FGLineContract[] GetFGLines() {
            object[] results = this.Invoke("GetFGLines", new object[0]);
            return ((FGLineContract[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetFGLines(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetFGLines", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public FGLineContract[] EndGetFGLines(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((FGLineContract[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISalesService/GetDeliveries", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
        public FGDeliveryContract[] GetDeliveries(System.DateTime dateSearch, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dateSearchSpecified) {
            object[] results = this.Invoke("GetDeliveries", new object[] {
                        dateSearch,
                        dateSearchSpecified});
            return ((FGDeliveryContract[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDeliveries(System.DateTime dateSearch, bool dateSearchSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDeliveries", new object[] {
                        dateSearch,
                        dateSearchSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public FGDeliveryContract[] EndGetDeliveries(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((FGDeliveryContract[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISalesService/GetUserData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
        public UserData[] GetUserData() {
            object[] results = this.Invoke("GetUserData", new object[0]);
            return ((UserData[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUserData(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUserData", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public UserData[] EndGetUserData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UserData[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISalesService/ChangeLoadingLine", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ChangeLoadingLine([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pickingId, int loadingLineNum, [System.Xml.Serialization.XmlIgnoreAttribute()] bool loadingLineNumSpecified) {
            object[] results = this.Invoke("ChangeLoadingLine", new object[] {
                        pickingId,
                        loadingLineNum,
                        loadingLineNumSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginChangeLoadingLine(string pickingId, int loadingLineNum, bool loadingLineNumSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ChangeLoadingLine", new object[] {
                        pickingId,
                        loadingLineNum,
                        loadingLineNumSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndChangeLoadingLine(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
    public partial class SalesTable {
        
        private System.Nullable<System.DateTime> deliveryDateField;
        
        private bool deliveryDateFieldSpecified;
        
        private string deliveryModeField;
        
        private string deliveryNameField;
        
        private string driverNameField;
        
        private bool halfPalletField;
        
        private bool halfPalletFieldSpecified;
        
        private SalesLine[] linesField;
        
        private int loadingLineField;
        
        private bool loadingLineFieldSpecified;
        
        private bool pickSameDimensionField;
        
        private bool pickSameDimensionFieldSpecified;
        
        private string pickingIdField;
        
        private string salesIdField;
        
        private string salesNameField;
        
        private System.DateTime startLoadingField;
        
        private bool startLoadingFieldSpecified;
        
        private System.DateTime stopLoadingField;
        
        private bool stopLoadingFieldSpecified;
        
        private string truckPlateField;
        
        private string truckTicketNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeliveryDate {
            get {
                return this.deliveryDateField;
            }
            set {
                this.deliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeliveryDateSpecified {
            get {
                return this.deliveryDateFieldSpecified;
            }
            set {
                this.deliveryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeliveryMode {
            get {
                return this.deliveryModeField;
            }
            set {
                this.deliveryModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeliveryName {
            get {
                return this.deliveryNameField;
            }
            set {
                this.deliveryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DriverName {
            get {
                return this.driverNameField;
            }
            set {
                this.driverNameField = value;
            }
        }
        
        /// <remarks/>
        public bool HalfPallet {
            get {
                return this.halfPalletField;
            }
            set {
                this.halfPalletField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HalfPalletSpecified {
            get {
                return this.halfPalletFieldSpecified;
            }
            set {
                this.halfPalletFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public SalesLine[] Lines {
            get {
                return this.linesField;
            }
            set {
                this.linesField = value;
            }
        }
        
        /// <remarks/>
        public int LoadingLine {
            get {
                return this.loadingLineField;
            }
            set {
                this.loadingLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LoadingLineSpecified {
            get {
                return this.loadingLineFieldSpecified;
            }
            set {
                this.loadingLineFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool PickSameDimension {
            get {
                return this.pickSameDimensionField;
            }
            set {
                this.pickSameDimensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PickSameDimensionSpecified {
            get {
                return this.pickSameDimensionFieldSpecified;
            }
            set {
                this.pickSameDimensionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PickingId {
            get {
                return this.pickingIdField;
            }
            set {
                this.pickingIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SalesId {
            get {
                return this.salesIdField;
            }
            set {
                this.salesIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SalesName {
            get {
                return this.salesNameField;
            }
            set {
                this.salesNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartLoading {
            get {
                return this.startLoadingField;
            }
            set {
                this.startLoadingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartLoadingSpecified {
            get {
                return this.startLoadingFieldSpecified;
            }
            set {
                this.startLoadingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StopLoading {
            get {
                return this.stopLoadingField;
            }
            set {
                this.stopLoadingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StopLoadingSpecified {
            get {
                return this.stopLoadingFieldSpecified;
            }
            set {
                this.stopLoadingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TruckPlate {
            get {
                return this.truckPlateField;
            }
            set {
                this.truckPlateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TruckTicketNum {
            get {
                return this.truckTicketNumField;
            }
            set {
                this.truckTicketNumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
    public partial class SalesLine {
        
        private string colorField;
        
        private bool exclusiveHalfPalletField;
        
        private bool exclusiveHalfPalletFieldSpecified;
        
        private string gradeField;
        
        private bool isHalfPalletField;
        
        private bool isHalfPalletFieldSpecified;
        
        private string itemIdField;
        
        private long lineRecIdField;
        
        private bool lineRecIdFieldSpecified;
        
        private string locationField;
        
        private InventByGrLocContract[] locationsField;
        
        private string nameField;
        
        private string pickingIdField;
        
        private string remarksField;
        
        private string salesIdField;
        
        private System.Nullable<decimal> salesQtyField;
        
        private bool salesQtyFieldSpecified;
        
        private System.Nullable<decimal> salesQtyBoxField;
        
        private bool salesQtyBoxFieldSpecified;
        
        private System.Nullable<decimal> salesQtyPalletField;
        
        private bool salesQtyPalletFieldSpecified;
        
        private System.Nullable<decimal> salesQtySQMField;
        
        private bool salesQtySQMFieldSpecified;
        
        private System.Nullable<decimal> salesQtySQMRemainingField;
        
        private bool salesQtySQMRemainingFieldSpecified;
        
        private System.Nullable<decimal> salesQtySQMReservedField;
        
        private bool salesQtySQMReservedFieldSpecified;
        
        private string salesUnitField;
        
        private string serialNumberField;
        
        private string siteField;
        
        private string sizeField;
        
        private string updateTypeField;
        
        private string updatedByField;
        
        private System.DateTime updatedDateField;
        
        private bool updatedDateFieldSpecified;
        
        private string warehouseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public bool ExclusiveHalfPallet {
            get {
                return this.exclusiveHalfPalletField;
            }
            set {
                this.exclusiveHalfPalletField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExclusiveHalfPalletSpecified {
            get {
                return this.exclusiveHalfPalletFieldSpecified;
            }
            set {
                this.exclusiveHalfPalletFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Grade {
            get {
                return this.gradeField;
            }
            set {
                this.gradeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsHalfPallet {
            get {
                return this.isHalfPalletField;
            }
            set {
                this.isHalfPalletField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsHalfPalletSpecified {
            get {
                return this.isHalfPalletFieldSpecified;
            }
            set {
                this.isHalfPalletFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
            }
        }
        
        /// <remarks/>
        public long LineRecId {
            get {
                return this.lineRecIdField;
            }
            set {
                this.lineRecIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LineRecIdSpecified {
            get {
                return this.lineRecIdFieldSpecified;
            }
            set {
                this.lineRecIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
        public InventByGrLocContract[] Locations {
            get {
                return this.locationsField;
            }
            set {
                this.locationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PickingId {
            get {
                return this.pickingIdField;
            }
            set {
                this.pickingIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SalesId {
            get {
                return this.salesIdField;
            }
            set {
                this.salesIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> SalesQty {
            get {
                return this.salesQtyField;
            }
            set {
                this.salesQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalesQtySpecified {
            get {
                return this.salesQtyFieldSpecified;
            }
            set {
                this.salesQtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> SalesQtyBox {
            get {
                return this.salesQtyBoxField;
            }
            set {
                this.salesQtyBoxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalesQtyBoxSpecified {
            get {
                return this.salesQtyBoxFieldSpecified;
            }
            set {
                this.salesQtyBoxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> SalesQtyPallet {
            get {
                return this.salesQtyPalletField;
            }
            set {
                this.salesQtyPalletField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalesQtyPalletSpecified {
            get {
                return this.salesQtyPalletFieldSpecified;
            }
            set {
                this.salesQtyPalletFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> SalesQtySQM {
            get {
                return this.salesQtySQMField;
            }
            set {
                this.salesQtySQMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalesQtySQMSpecified {
            get {
                return this.salesQtySQMFieldSpecified;
            }
            set {
                this.salesQtySQMFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> SalesQtySQMRemaining {
            get {
                return this.salesQtySQMRemainingField;
            }
            set {
                this.salesQtySQMRemainingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalesQtySQMRemainingSpecified {
            get {
                return this.salesQtySQMRemainingFieldSpecified;
            }
            set {
                this.salesQtySQMRemainingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> SalesQtySQMReserved {
            get {
                return this.salesQtySQMReservedField;
            }
            set {
                this.salesQtySQMReservedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalesQtySQMReservedSpecified {
            get {
                return this.salesQtySQMReservedFieldSpecified;
            }
            set {
                this.salesQtySQMReservedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SalesUnit {
            get {
                return this.salesUnitField;
            }
            set {
                this.salesUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UpdateType {
            get {
                return this.updateTypeField;
            }
            set {
                this.updateTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UpdatedBy {
            get {
                return this.updatedByField;
            }
            set {
                this.updatedByField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UpdatedDate {
            get {
                return this.updatedDateField;
            }
            set {
                this.updatedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpdatedDateSpecified {
            get {
                return this.updatedDateFieldSpecified;
            }
            set {
                this.updatedDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Warehouse {
            get {
                return this.warehouseField;
            }
            set {
                this.warehouseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
    public partial class InventByGrLocContract : XppObjectBase {
        
        private string gradeFieldField;
        
        private string locationIdFieldField;
        
        private decimal onHandFieldField;
        
        private bool onHandFieldSpecified1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gradeField {
            get {
                return this.gradeFieldField;
            }
            set {
                this.gradeFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string locationIdField {
            get {
                return this.locationIdFieldField;
            }
            set {
                this.locationIdFieldField = value;
            }
        }
        
        /// <remarks/>
        public decimal onHandField {
            get {
                return this.onHandFieldField;
            }
            set {
                this.onHandFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("onHandFieldSpecified")]
        public bool onHandFieldSpecified1 {
            get {
                return this.onHandFieldSpecified1Field;
            }
            set {
                this.onHandFieldSpecified1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FGDeliveryContract))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FGLineContract))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomerDeliveryContract))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PalletItemContract))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InventByGrLocContract))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
    public partial class XppObjectBase {
        
        private PropertyChangedEventHandler propertyChangedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PropertyChangedEventHandler PropertyChanged {
            get {
                return this.propertyChangedField;
            }
            set {
                this.propertyChangedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.ComponentModel")]
    public partial class PropertyChangedEventHandler : MulticastDelegate {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyChangedEventHandler))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial class MulticastDelegate : Delegate {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MulticastDelegate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyChangedEventHandler))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial class Delegate {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlQualifiedName factoryTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        public System.Xml.XmlQualifiedName FactoryType {
            get {
                return this.factoryTypeField;
            }
            set {
                this.factoryTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
    public partial class UserData {
        
        private string passwordField;
        
        private string userNameField;
        
        private string userTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
    public partial class FGDeliveryContract : XppObjectBase {
        
        private System.DateTime deliveryDateFieldField;
        
        private bool deliveryDateFieldSpecified1Field;
        
        private int lineNumFieldField;
        
        private bool lineNumFieldSpecified1Field;
        
        private string packingSlipNumFieldField;
        
        private string pickingIdFieldField;
        
        private string quantityInPalletsFieldField;
        
        private string quantityInSQMFieldField;
        
        private string salesIdFieldField;
        
        private string ticketFieldField;
        
        private string truckDriverFieldField;
        
        private string truckPlateNumFieldField;
        
        /// <remarks/>
        public System.DateTime deliveryDateField {
            get {
                return this.deliveryDateFieldField;
            }
            set {
                this.deliveryDateFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deliveryDateFieldSpecified")]
        public bool deliveryDateFieldSpecified1 {
            get {
                return this.deliveryDateFieldSpecified1Field;
            }
            set {
                this.deliveryDateFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public int lineNumField {
            get {
                return this.lineNumFieldField;
            }
            set {
                this.lineNumFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lineNumFieldSpecified")]
        public bool lineNumFieldSpecified1 {
            get {
                return this.lineNumFieldSpecified1Field;
            }
            set {
                this.lineNumFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string packingSlipNumField {
            get {
                return this.packingSlipNumFieldField;
            }
            set {
                this.packingSlipNumFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pickingIdField {
            get {
                return this.pickingIdFieldField;
            }
            set {
                this.pickingIdFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string quantityInPalletsField {
            get {
                return this.quantityInPalletsFieldField;
            }
            set {
                this.quantityInPalletsFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string quantityInSQMField {
            get {
                return this.quantityInSQMFieldField;
            }
            set {
                this.quantityInSQMFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string salesIdField {
            get {
                return this.salesIdFieldField;
            }
            set {
                this.salesIdFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ticketField {
            get {
                return this.ticketFieldField;
            }
            set {
                this.ticketFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string truckDriverField {
            get {
                return this.truckDriverFieldField;
            }
            set {
                this.truckDriverFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string truckPlateNumField {
            get {
                return this.truckPlateNumFieldField;
            }
            set {
                this.truckPlateNumFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
    public partial class FGLineContract : XppObjectBase {
        
        private string fGLineNameFieldField;
        
        private int fGLineNumberFieldField;
        
        private bool fGLineNumberFieldSpecified1Field;
        
        private int onGateNumFieldField;
        
        private bool onGateNumFieldSpecified1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fGLineNameField {
            get {
                return this.fGLineNameFieldField;
            }
            set {
                this.fGLineNameFieldField = value;
            }
        }
        
        /// <remarks/>
        public int fGLineNumberField {
            get {
                return this.fGLineNumberFieldField;
            }
            set {
                this.fGLineNumberFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fGLineNumberFieldSpecified")]
        public bool fGLineNumberFieldSpecified1 {
            get {
                return this.fGLineNumberFieldSpecified1Field;
            }
            set {
                this.fGLineNumberFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public int onGateNumField {
            get {
                return this.onGateNumFieldField;
            }
            set {
                this.onGateNumFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("onGateNumFieldSpecified")]
        public bool onGateNumFieldSpecified1 {
            get {
                return this.onGateNumFieldSpecified1Field;
            }
            set {
                this.onGateNumFieldSpecified1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
    public partial class CustomerDeliveryContract : XppObjectBase {
        
        private string customerAccountFieldField;
        
        private string customerNameFieldField;
        
        private string packingSlipNumFieldField;
        
        private decimal quantityFieldField;
        
        private bool quantityFieldSpecified1Field;
        
        private int trucksFieldField;
        
        private bool trucksFieldSpecified1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerAccountField {
            get {
                return this.customerAccountFieldField;
            }
            set {
                this.customerAccountFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerNameField {
            get {
                return this.customerNameFieldField;
            }
            set {
                this.customerNameFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string packingSlipNumField {
            get {
                return this.packingSlipNumFieldField;
            }
            set {
                this.packingSlipNumFieldField = value;
            }
        }
        
        /// <remarks/>
        public decimal quantityField {
            get {
                return this.quantityFieldField;
            }
            set {
                this.quantityFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("quantityFieldSpecified")]
        public bool quantityFieldSpecified1 {
            get {
                return this.quantityFieldSpecified1Field;
            }
            set {
                this.quantityFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public int trucksField {
            get {
                return this.trucksFieldField;
            }
            set {
                this.trucksFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("trucksFieldSpecified")]
        public bool trucksFieldSpecified1 {
            get {
                return this.trucksFieldSpecified1Field;
            }
            set {
                this.trucksFieldSpecified1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
    public partial class PalletItemContract : XppObjectBase {
        
        private string serialFieldField;
        
        private string updatedByFieldField;
        
        private System.DateTime updatedDateFieldField;
        
        private bool updatedDateFieldSpecified1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string serialField {
            get {
                return this.serialFieldField;
            }
            set {
                this.serialFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string updatedByField {
            get {
                return this.updatedByFieldField;
            }
            set {
                this.updatedByFieldField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime updatedDateField {
            get {
                return this.updatedDateFieldField;
            }
            set {
                this.updatedDateFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("updatedDateFieldSpecified")]
        public bool updatedDateFieldSpecified1 {
            get {
                return this.updatedDateFieldSpecified1Field;
            }
            set {
                this.updatedDateFieldSpecified1Field = value;
            }
        }
    }
}
